framework:
  messenger:
    transports:
      async_priority_high: '%env(MESSENGER_TRANSPORT_DSN)%'
      async_normal:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        options:
          queue_name: normal_priority


    routing:
      # Route your messages to the transports
      'App\Message\UserRegistration': async
