version: '3.5'
services:
    loterioma_lobby:
        build: .docker/php
        container_name: loterioma_lobby
        stdin_open: true
        tty: true
        ports:
          - 5701:80
        environment:
          - APACHE_DOCUMENT_ROOT=/var/www/html/public
        volumes:
          - .:/var/www/html
        networks:
          - my-proxy-net

networks:
    my-proxy-net:
        external: true
        name: loterioma-net